// <auto-generated />
using System;
using Lab5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab5.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260503214646_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Lab5.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "British author",
                            BirthDate = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "J.K.",
                            LastName = "Rowling",
                            Nationality = "British",
                            Website = "https://www.jkrowling.com"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "American author",
                            BirthDate = new DateTime(1948, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "George",
                            LastName = "R. R. Martin",
                            Nationality = "American",
                            Website = "https://www.georgerrmartin.com"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "English author",
                            BirthDate = new DateTime(1892, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "J.R.R.",
                            LastName = "Tolkien",
                            Nationality = "English",
                            Website = "https://www.tolkien.co.uk"
                        });
                });

            modelBuilder.Entity("Lab5.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "A young wizard's journey",
                            Isbn = "978-0-7475-3269-9",
                            Language = "English",
                            PageCount = 309,
                            PublishedOn = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 1,
                            Status = 0,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Description = "Epic fantasy drama",
                            Isbn = "978-0-553-10354-1",
                            Language = "English",
                            PageCount = 694,
                            PublishedOn = new DateTime(1996, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 2,
                            Status = 0,
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Description = "Epic fantasy adventure",
                            Isbn = "978-0-544-00362-6",
                            Language = "English",
                            PageCount = 423,
                            PublishedOn = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 3,
                            Status = 0,
                            Title = "The Fellowship of the Ring"
                        });
                });

            modelBuilder.Entity("Lab5.Models.BookGenre", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BookGenres");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            GenreId = 1,
                            AddedAt = new DateTime(2026, 5, 3, 23, 46, 45, 596, DateTimeKind.Local).AddTicks(6281)
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 1,
                            AddedAt = new DateTime(2026, 5, 3, 23, 46, 45, 598, DateTimeKind.Local).AddTicks(9416)
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 3,
                            AddedAt = new DateTime(2026, 5, 3, 23, 46, 45, 598, DateTimeKind.Local).AddTicks(9435)
                        },
                        new
                        {
                            BookId = 3,
                            GenreId = 1,
                            AddedAt = new DateTime(2026, 5, 3, 23, 46, 45, 598, DateTimeKind.Local).AddTicks(9438)
                        });
                });

            modelBuilder.Entity("Lab5.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Audience = "Young Adults",
                            Description = "Fantastical worlds and magic",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Audience = "Adults",
                            Description = "Future and space",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Audience = "Adults",
                            Description = "Human conflicts",
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("Lab5.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FoundedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "London",
                            ContactEmail = "info@bloomsbury.com",
                            Country = "UK",
                            FoundedOn = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bloomsbury",
                            Website = "https://www.bloomsbury.com"
                        },
                        new
                        {
                            Id = 2,
                            City = "New York",
                            ContactEmail = "info@bantambooks.com",
                            Country = "USA",
                            FoundedOn = new DateTime(1945, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bantam Books",
                            Website = "https://www.bantambooks.com"
                        },
                        new
                        {
                            Id = 3,
                            City = "London",
                            ContactEmail = "info@allenandunwin.com",
                            Country = "UK",
                            FoundedOn = new DateTime(1914, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Allen & Unwin",
                            Website = "https://www.allenandunwin.com"
                        });
                });

            modelBuilder.Entity("Lab5.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sentiment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Comment = "Best book ever",
                            IsRecommended = true,
                            ReviewedAt = new DateTime(2026, 5, 3, 23, 46, 45, 599, DateTimeKind.Local).AddTicks(2571),
                            Score = 5,
                            Sentiment = 3,
                            Title = "Amazing!",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            Comment = "Very engaging",
                            IsRecommended = true,
                            ReviewedAt = new DateTime(2026, 5, 3, 23, 46, 45, 599, DateTimeKind.Local).AddTicks(3278),
                            Score = 4,
                            Sentiment = 2,
                            Title = "Great read",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            Comment = "A masterpiece",
                            IsRecommended = true,
                            ReviewedAt = new DateTime(2026, 5, 3, 23, 46, 45, 599, DateTimeKind.Local).AddTicks(3286),
                            Score = 5,
                            Sentiment = 3,
                            Title = "Epic!",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Lab5.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteGenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPremiumMember")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            FavoriteGenre = "Fantasy",
                            FullName = "Alice Reader",
                            IsPremiumMember = true,
                            JoinedAt = new DateTime(2026, 5, 3, 23, 46, 45, 599, DateTimeKind.Local).AddTicks(984),
                            ReputationPoints = 150,
                            Username = "reader1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            FavoriteGenre = "Science Fiction",
                            FullName = "Bob Smith",
                            IsPremiumMember = false,
                            JoinedAt = new DateTime(2026, 5, 3, 23, 46, 45, 599, DateTimeKind.Local).AddTicks(1528),
                            ReputationPoints = 80,
                            Username = "reader2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carol@example.com",
                            FavoriteGenre = "Fantasy",
                            FullName = "Carol White",
                            IsPremiumMember = true,
                            JoinedAt = new DateTime(2026, 5, 3, 23, 46, 45, 599, DateTimeKind.Local).AddTicks(1536),
                            ReputationPoints = 200,
                            Username = "reader3"
                        });
                });

            modelBuilder.Entity("Lab5.Models.Book", b =>
                {
                    b.HasOne("Lab5.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab5.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Lab5.Models.BookGenre", b =>
                {
                    b.HasOne("Lab5.Models.Book", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab5.Models.Genre", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Lab5.Models.Review", b =>
                {
                    b.HasOne("Lab5.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab5.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lab5.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Lab5.Models.Book", b =>
                {
                    b.Navigation("BookGenres");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Lab5.Models.Genre", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("Lab5.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Lab5.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}

